const projects = [
  {
    id: 1,
    title: 'Address Book',
    stack: 'Javascript | Tailwind',
    imageUrl: '/images/robot.webp',
    alt: 'Coffee',
    description:
      'A simple address book that stores the information in your local storage. Built in JavaScript and styled using Tailwind CSS.',
    GitHub: 'https://github.com/boamatule/adressbook_Challenge/tree/01-project-setup',
    URL: 'https://addressbookit.netlify.app/',
  },
  {
    id: 2,
    title: 'Coffee Connoisseur',
    stack: 'Nextjs | GraphSQL | Serverless',
    imageUrl: '/images/chingu_boa.webp',
    alt: 'Coffee',
    description: 'News for everyone, by anyone, from everywhere! A peer-to-peer review online newspaper.',
    URL: 'https://github.com/SnailCoder1/atm_challenge-1',
  },
  {
    id: 3,
    title: 'BMI Calculator',
    imageUrl: '/images/space.webp',
    alt: 'Coffee',
    stack: 'React | Cypress | Semantic UI',
    description: 'Build in React and Acceptance testing using Cypress. Styled using Semantic UI for React',
    GitHub: 'https://github.com/SnailCoder1/bmi_calculator_reactJs',
    URL: 'https://1bmi.netlify.app/',
  },
  {
    id: 4,
    title: 'Library',
    imageUrl: '/images/chingu_boa.webp',
    alt: 'Coffee',
    stack: 'Ruby on Rails',
    description: 'Library management. The database is stored in a YAML file.',
    GitHub: 'https://github.com/SnailCoder1/library-challenge',
    URL: 'https://github.com/boamatule/library-challenge',
  },
  {
    id: 5,
    title: 'Cooper Calculator',
    stack: ' ReactJs | Semantic UI | Heroku | Rails',
    imageUrl: '/images/chingu_boa.webp',
    alt: 'Coffee',
    description:
      'Famous Cooper test built in ReactJs. Back-end API built in Ruby on Rails. Styled using Semantic UI. Hosted in Heroku.',
    GitHub: 'https://github.com/SnailCoder1/Cooper_Client',
    URL: 'https://github.com/SnailCoder1/atm_challenge-1',
  },
  {
    id: 6,
    title: 'Cat-BnB',
    stack: 'ReactJs | Semantic UI | Heroku | Ruby on Rails | Semaphore',
    imageUrl: '/images/chingu_boa.webp',
    alt: 'Coffee',
    description: 'An AirBNB for cats.',
    GitHub: '',
    URL: 'https://github.com/SnailCoder1/atm_challenge-1',
  },
  {
    id: 7,
    title: 'MealsToGo',
    stack: 'React Native  | Firebase | Expo',
    imageUrl: '/images/chingu_boa.webp',
    alt: 'Coffee',
    description:
      'A simple prototype of an Automatic Teller Machine (ATM) system with limited functionality built in Ruby program and RSpec',
    GitHub: 'https://github.com/SnailCoder1/atm_challenge-1',
    URL: 'https://github.com/SnailCoder1/atm_challenge-1',
  },
  {
    id: 8,
    title: 'Blog',
    stack: 'ReactJs | NodeJs | MongoDB |',
    imageUrl: '/images/chingu_boa.webp',
    alt: 'Coffee',
    description: 'Blog built in ReactJs and Backended using MongoDB',
    GitHub: 'https://github.com/boamatule/raw-details-blog',
    URL: 'https://github.com/SnailCoder1/atm_challenge-1',
  },
  {
    id: 9,
    title: 'Newsroom',
    stack: 'ReactJs | NodeJs | MongoDB |',
    imageUrl: '/images/chingu_boa.webp',
    alt: 'Coffee',
    description: 'Blog built in ReactJs and Backended using MongoDB',
    GitHub: 'https://github.com/boamatule/raw-details-blog',
    URL: 'https://github.com/SnailCoder1/atm_challenge-1',
  },
  {
    id: 10,
    title: 'Kind Like Netflix',
    stack: 'Nextjs | Serveless | Framer | GraphSQL | Redis |Hasura| Vercel | Serveless |',
    imageUrl: '/images/chingu_boa.webp',
    alt: 'Coffee',
    description: 'Blog built in ReactJs and Backended using MongoDB',
    GitHub: 'https://github.com/boamatule/raw-details-blog',
    URL: 'https://github.com/SnailCoder1/atm_challenge-1',
  },
];

export default projects;
