const projects = [
  {
    id: 1,
    title: 'Newsroom | Reactjs | Cypress | Rails',
    stack1: 'Reactjs',
    stack2: 'Cypress',
    stack3: 'Rails',
    stack4: 'Jest',
    imageUrl: '/images/chingu_boa.png',
    link1: '',
    link2: '',
    description: 'News for everyone, by anyone, from everywhere! A peer-to-peer review online newspaper.',
    URL: 'https://glocal-news.netlify.com/news',
  },
  {
    id: 2,
    title: 'Address Book | Javascript | Tailwind',
    stack: 'Javascript | Tailwind',
    imageUrl: '/images/robot.png',
    description:
      'A simple address book that stores the information in your local storage. Built in JavaScript and styled using Tailwind CSS.',
    GitHub: 'https://github.com/boamatule/adressbook_Challenge/tree/01-project-setup',
    URL: 'https://addressbookit.netlify.app/',
  },
  {
    id: 3,
    title: 'BMI Calculator',
    imageUrl: '/images/code_review.svg',
    stack: 'React | Cypress | Semantic UI',
    description: 'Build in React and Acceptance testing using Cypress. Styled using Semantic UI for React',
    GitHub: 'https://github.com/SnailCoder1/bmi_calculator_reactJs',
    URL: 'https://1bmi.netlify.app/',
  },
  {
    id: 4,
    title: 'Library | Ruby on Rails ',
    imageUrl: '/images/code_review.svg',
    stack: 'Ruby on Rails',
    description: 'Library management. The database is stored in a YAML file.',
    GitHub: 'https://github.com/SnailCoder1/library-challenge',
    URL: 'https://github.com/boamatule/library-challenge',
  },
  {
    id: 5,
    title: 'Cooper Calculator | ReactJs | Semantic UI | Heroku | Rails',
    stack: ' ReactJs | Semantic UI | Heroku | Rails',
    imageUrl: '/images/boa.png',
    description:
      'Famous Cooper test built in ReactJs. Back-end API built in Ruby on Rails. Styled using Semantic UI. Hosted in Heroku.',
    GitHub: 'https://github.com/SnailCoder1/Cooper_Client',
    URL: 'https://1cooper.netlify.com/',
  },
  {
    id: 6,
    title: 'Cat-BnB | ReactJs | Semantic UI | Heroku | Ruby on Rails | Semaphore',
    stack: 'ReactJs | Semantic UI | Heroku | Ruby on Rails | Semaphore',
    imageUrl: '/images/logo.png',
    description: 'An AirBNB for cats.',
    GitHub: '',
    URL: 'https://kattbnb.herokuapp.com/',
  },
  {
    id: 7,
    title: 'ATM | Ruby on Rails  | RSpec',
    imageUrl: '/images/code_review.svg',
    description:
      'A simple prototype of an Automatic Teller Machine (ATM) system with limited functionality built in Ruby program and RSpec',
    GitHub: 'https://github.com/SnailCoder1/atm_challenge-1',
    URL: '',
  },
  {
    id: 8,
    title: 'Blog | ReactJs | NodeJs | MongoDB | ',
    imageUrl: '/images/code_review.svg',
    description: 'Blog built in ReactJs and Backended using MongoDB',
    GitHub: 'https://github.com/boamatule/raw-details-blog',
    URL: '',
  },
  {
    id: 9,
    title: 'Blog | ReactJs | NodeJs | MongoDB | ',
    imageUrl: '/images/logo.png',
    description: 'Blog built in ReactJs and Backended using MongoDB',
    GitHub: 'https://github.com/boamatule/raw-details-blog',
    URL: '',
  },
];

export default projects;
