const projects = [
  {
    id: 1,
    title: 'Crwn Clothing Platform',
    stack: 'React | Firebase  | Stripe  | Styled-Components',
    imageUrl: '/images/crown.svg',
    alt: 'Clothes',
    description:
      'A simple address book that stores the information in your local storage. Built in JavaScript and styled using Tailwind CSS.',
    sourceCodeUrl: 'https://github.com/boamatule/crwn-clothing',
    URL: 'https://crwn-live-clothing-app.herokuapp.com/',
  },
  {
    id: 2,
    title: 'Coffee Connoisseur',
    stack: 'Nextjs | GraphSQL | Serverless',
    imageUrl: '/images/chingu_boa.webp',
    alt: 'Coffee',
    description: 'News for everyone, by anyone, from everywhere! A peer-to-peer review online newspaper.',
    sourceCodeUrl: 'https://github.com/boamatule/Coffee_Connoisseur_Nextjs',
    URL: '',
  },
  {
    id: 3,
    title: 'Newsroom',
    stack: 'React | Ruby on Rails | Redis |',
    imageUrl: '/images/unitest.webp',
    alt: 'Newsroom',
    description: 'Blog built in ReactJs and Backended using MongoDB',
    sourceCodeUrl: 'https://github.com/boamatule/Glocal_news-Client',
    URL: 'https://glocal-news.netlify.app/news',
  },
  {
    id: 4,
    title: 'Kind Like Netflix',
    stack:
      'Nextjs | Serveless | Framer | GraphQL | Redis |Hasura| Vercel | Serveless | Magic | ISG | JWT | Framer | React Hooks |',
    imageUrl: '/images/space.webp',
    alt: 'space',
    description: 'Blog built in ReactJs and Backended using MongoDB',
    sourceCodeUrl: 'https://github.com/boamatule/discover_videos_nextjs',
    URL: '',
  },
  {
    id: 5,
    title: 'BMI Calculator',
    imageUrl: '/images/bmi.svg',
    alt: 'Coffee',
    stack: 'React | Cypress | Semantic UI',
    description: 'Build in React and Acceptance testing using Cypress. Styled using Semantic UI for React',
    sourceCodeUrl: 'https://github.com/SnailCoder1/bmi_calculator_reactJs',
    URL: 'https://1bmi.netlify.app/',
  },
  {
    id: 6,
    title: 'Library',
    imageUrl: '/images/library.svg',
    alt: 'Coffee',
    stack: 'Ruby on Rails',
    description: 'Library management. The database is stored in a YAML file.',
    sourceCodeUrl: 'https://github.com/SnailCoder1/library-challenge',
    URL: 'https://github.com/boamatule/library-challenge',
  },
  {
    id: 7,
    title: 'Cooper Calculator',
    stack: ' React | Semantic UI | Heroku | Ruby on Rails',
    imageUrl: '/images/cooper.svg',
    alt: 'Cooper',
    description:
      'Famous Cooper test built in ReactJs. Back-end API built in Ruby on Rails. Styled using Semantic UI. Hosted in Heroku.',
    sourceCodeUrl: 'https://github.com/SnailCoder1/Cooper_Client',
    URL: 'https://github.com/SnailCoder1/atm_challenge-1',
  },
  {
    id: 9,
    title: 'Cat-BnB',
    stack: 'ReactJs | Semantic UI | Heroku | Ruby on Rails | Semaphore',
    imageUrl: '/images/cat.svg',
    alt: 'Coffee',
    description: 'An AirBNB for cats.',
    sourceCodeUrl: 'https://github.com/boamatule/cat-bnb',
    URL: 'https://kattbnb.herokuapp.com/',
  },
  {
    id: 9,
    title: 'MealsToGo',
    stack: 'React Native  | Firebase | Expo',
    imageUrl: '/images/mealstogo.webp',
    alt: 'Meals',
    description:
      'A simple prototype of an Automatic Teller Machine (ATM) system with limited functionality built in Ruby program and RSpec',
    sourceCodeUrl: 'https://github.com/boamatule/MealsToGo',
    URL: '',
  },
  {
    id: 10,
    title: 'Blog',
    stack: 'ReactJs | NodeJs | MongoDB |',
    imageUrl: '/images/blog.svg',
    alt: 'Coffee',
    description: 'Blog built in ReactJs and Backended using MongoDB',
    sourceCodeUrl: 'https://github.com/boamatule/raw-details-blog',
    URL: '',
  },
];

export default projects;
